# .eas/workflows/deploy.yml

name: Deploy

on:
  push:
    branches: ['master']  # Trigger this workflow when pushing to main

jobs:
  deploy:
    type: deploy        # Built-in job type from EAS for deploying
    name: Deploy        # Just a label
    environment: production  # Use environment variables from your 'production' env in Expo
    params:
      prod: true        # Pass a custom flag (optional)
